apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbuchanan
  labels:
    app: javaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: container-buchanan
        image: public.ecr.aws/p5u5p5h0/buchananecr:9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svcbuchanan
  labels:
    app: javaapp
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: javaapp